# Generated by Django 5.2.1 on 2025-05-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_producto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
    ]
