# Generated by Django 5.2.1 on 2025-06-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0009_kit_alter_producto_stock_kitcomponente_kit_piezas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_elemento',
            field=models.CharField(choices=[('pieza', 'Pieza'), ('lote', 'Lote'), ('kit', 'Kit')], default='pieza', max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.producto'),
        ),
    ]
