# Generated by Django 5.2.1 on 2025-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0010_kit_estado_movimiento_tipo_elemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='motivo_movimiento',
            field=models.CharField(default=True),
        ),
    ]
