# Generated by Django 5.2.1 on 2025-06-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0011_movimiento_motivo_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
