# Generated by Django 5.2.1 on 2025-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0013_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.TextField(blank=True),
        ),
    ]
