# Generated by Django 5.2.1 on 2025-06-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0014_producto_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10),
        ),
    ]
